### PR TITLE
rm unused class, shorten trans(), correct links, add screenshots

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Remove unused FlashBagInterface, CustomerException class.<br>Shorten trans() call. <br> Correct devdocs links (follow master repo). <br> Add screenshots for how the new option looks in list and form. 
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes {paste the issue here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
Ooooh that looks really cool @leemyongpakvn 

I must test it on localhost but everything looks valid

**Comment by leemyongpakvn** [comment]
@matks I tested it on my localhost successfully. It will be better if you can test it on your localhost again to make sure everything goes well.
FYI, I see you transferred this module to [demoextendsymfonyform3](https://github.com/PrestaShop/example-modules/tree/master/demoextendsymfonyform3), but the original `democqrshooksusage` phrase left in the transfer create some errors on my localhost, especially this one:
`RouteNotFoundException
Unable to generate a URL for the named route "ps_democqrshooksusage_toggle_is_allowed_for_review" as such route does not exist.` So I think we need some more tweak and test for demoextendsymfonyform3.

**Comment by matks** [comment]
> @matks I tested it on my localhost successfully. It will be better if you can test it on your localhost again to make sure everything goes well. FYI, I see you transferred this module to [demoextendsymfonyform3](https://github.com/PrestaShop/example-modules/tree/master/demoextendsymfonyform3), but the original `democqrshooksusage` phrase left in the transfer create some errors on my localhost, especially this one: `RouteNotFoundException Unable to generate a URL for the named route "ps_democqrshooksusage_toggle_is_allowed_for_review" as such route does not exist.` So I think we need some more tweak and test for demoextendsymfonyform3.

Indeed I missed that this is the "old" repository 😅 do you think you can bring your changes to demoextendsymfonyform3? I think I forgot to close this repository.

**Comment by leemyongpakvn** [comment]
@matks Closed since Transferred to the new repository. Don't forget to delete the old one when you have time. :joy:

**Pull request closed without merging**
